### ISSUE TITLE
Questions related to the implementation

### ISSUE THREAD

**Issue by xixiaofinland** [aheber/tree-sitter-sfapex#16]
I will have questions along the journey of understanding this repo, so create this thread to shoot them 🍡 

Question:

How do you define the colors for those captures inside `highlights.scm` or are those out of box? I see a need to fine-tune some of the captures and assign them to different colors.

I know in Nvim config files, it can be done. Just wonder how you did it. Thanks! https://www.reddit.com/r/neovim/comments/m8zedt/how_to_change_a_particular_syntax_token_highlight/

@aheber

**Comment by aheber** [comment]
I don't define color, the highlights assign a "category" for the tag but coloring in the NVIM theme assigns the color per tag/tag group (I don't know how NVIM Treesitter maps my tags to the TSKeyword style tagging seen in themes). I tried to align the included highlighting with https://code.visualstudio.com/api/language-extensions/semantic-highlight-guide but that may not be correct for NVIM or other. 

NVIM Treesitter seems to include a different set of Highlights as part of it's source code. https://github.com/nvim-treesitter/nvim-treesitter/blob/master/queries/javascript/highlights.scm

It seems like the expectation is for the parser and the tool-specific highlights to be able to be kept separate due to the possibility that NVIM has different needs? I'm mostly guessing here but based on their repo it seems kinda like that.

**Comment by xixiaofinland** [comment]
> I don't define color, the highlights assign a "category" for the tag but coloring in the NVIM theme assigns the color per tag/tag group (I don't know how NVIM Treesitter maps my tags to the TSKeyword style tagging seen in themes). I tried to align the included highlighting with https://code.visualstudio.com/api/language-extensions/semantic-highlight-guide but that may not be correct for NVIM or other.
> 
> NVIM Treesitter seems to include a different set of Highlights as part of it's source code. https://github.com/nvim-treesitter/nvim-treesitter/blob/master/queries/javascript/highlights.scm
> 
> It seems like the expectation is for the parser and the tool-specific highlights to be able to be kept separate due to the possibility that NVIM has different needs? I'm mostly guessing here but based on their repo it seems kinda like that.

I found the list of default capture annotations https://github.com/nvim-treesitter/nvim-treesitter/blob/master/CONTRIBUTING.md#highlights  

Another question is the syntax highlight of the injected SOQL in Apex.  Not sure if you had the need.


The parser detects the `soql query` node well and the language injection in `hightlights.scm` is defined according to the official doc, but it doesn't work.

SOQL in its own file works (the mos right window in the screenshot)

![Image 004](https://github.com/aheber/tree-sitter-sfapex/assets/13655323/5c568412-a0a4-4a45-b666-97042b730863)

**Comment by xixiaofinland** [comment]
It seems the SOQL in `for` condition is not parsed correctly. @aheber 
![Image 005](https://github.com/aheber/tree-sitter-sfapex/assets/13655323/2223acf0-0c37-48ab-be97-cd187445a738)

**Comment by aheber** [comment]
@xixiaofinland are you having that parsed as SOQL vs parsing as Apex?
If I parse as Apex then it is fine. If I parse as SOQL then I get what you are reporting.
![image](https://github.com/aheber/tree-sitter-sfapex/assets/2173116/f59551d2-f303-49d2-93c3-6e717173a1cf)
https://aheber.github.io/tree-sitter-sfapex/playground/

SOQL inside of Apex is part of Apex. The SOQL parser doesn't pull SOQL out of Apex, the entire contents of the buffer have to be valid SOQL. The content you show in your screenshot is Apex which happens to hold nested SOQL as part of the Apex grammar so it needs to be parsed with the Apex parser.

Hope that helps explain what you're seeing.

**Comment by xixiaofinland** [comment]
I think I'm using the Apex parser otherwise the entire Apex file won't work. But it's easy to verify, I will get back later.

**Comment by xixiaofinland** [comment]
It seems the Apex parser compiled in Nvim doesn't understand SOQL and SOSL, so it fails in the embedded SOQL and SOSL.

**Comment by xixiaofinland** [comment]
I created an issue in nvim-tree-sitter, not sure if any help there: https://github.com/nvim-treesitter/nvim-treesitter/issues/5383

**Comment by aheber** [comment]
This will be a configuration problem. For now you should probably only register the Apex parser. The SOQL parser isn't necessary for Apex files. (It is baked in to the Apex parser)

If it isn't registering SOQL does that mean it throws errors or it doesn't highlight correctly?

I'm assuming it doesn't highlight correctly and that is probably more because we need to use both sets of highlight queries to get the desired results. I think you might be able to register both files but you might find it easiest to just cut the highlight queries from the SOQL and SOSL and past them into the bottom of the Apex highlights file.

**Comment by aheber** [comment]
I'll have to think if there is an easier way to get the highlights together for Apex. It does seem like it should have everything though I don't to make it a maintenance nightmare.

**Comment by xixiaofinland** [comment]
> I'll have to think if there is an easier way to get the highlights together for Apex. It does seem like it should have everything though I don't to make it a maintenance nightmare.

ohh, you know what? I already got the nested SOQL highlight work in Apex. 
Nvim-tree-sitter uses highlight query syntax differently from upstream.

**Comment by xixiaofinland** [comment]
> This will be a configuration problem. For now you should probably only register the Apex parser. The SOQL parser isn't necessary for Apex files. (It is baked in to the Apex parser)
> 
> If it isn't registering SOQL does that mean it throws errors or it doesn't highlight correctly?
> 
> I'm assuming it doesn't highlight correctly and that is probably more because we need to use both sets of highlight queries to get the desired results. I think you might be able to register both files but you might find it easiest to just cut the highlight queries from the SOQL and SOSL and past them into the bottom of the Apex highlights file

**Comment by xixiaofinland** [comment]
> This will be a configuration problem. For now you should probably only register the Apex parser. The SOQL parser isn't necessary for Apex files. (It is baked in to the Apex parser)
> 
> If it isn't registering SOQL does that mean it throws errors or it doesn't highlight correctly?
> 
> I'm assuming it doesn't highlight correctly and that is probably more because we need to use both sets of highlight queries to get the desired results. I think you might be able to register both files but you might find it easiest to just cut the highlight queries from the SOQL and SOSL and past them into the bottom of the Apex highlights file.

Not sure what you mean, as long as the tree nodes are correctly parsed in Apex (including nested soql and sosl), syntax highlight for SOQL/SOSL is trivial to add into the apex's highlights.scm.

**Comment by xixiaofinland** [comment]
I removed `sosl` and `soql` it seems the tree is correct now!
![Screenshot 2023-09-12 at 17 42 21](https://github.com/aheber/tree-sitter-sfapex/assets/13655323/6c8a8015-0416-49bd-b220-215bb55ca288)

**Comment by xixiaofinland** [comment]
> Eventually you can work out registering SOQL and SOSL and independent file suffix associations. (.soql and .sosl respectively) You could treat those as different efforts though because from the perspective of treesitter they are totally separate once compiled.
> 
> As for forking, if it were me I'd think about my project as two parts. The Parser and the Highlights. My understanding is that the parser should be fine to share and can be based here, nvim-treesitter understands how to download and install from GitHub once the project is registered correctly (I think). The highlights should probably be forked and eventually maintained in the nvim-treesitter repo, which seems to be their common practice. I'd wait until you're happy with the behavior then get it added there.
> 
> The benefit to centering them there and getting Apex registered as a proper parser and highlights is if someone comes to the project later they will be able to easily install nvim-treesitter and Apex will effectively just work like any other language. They won't need to do anything fancy or rediscover how this all actually functions, like you're doing.
> 
> I don't mind if you fork everything and make it work for your purposes but if I'm missing significant stuff in the parser I'd likely just want to get it fixed and that would hopefully benefit everyone that might depend on it.

You already have the parser base set perfectly, totally agree there is no point in forking the parsers.
I also agree it's best to keep the 3 languages separated as they are now.

In terms of the parsing issue above, once the SOQL parser is inquired by Apex parser because the nested SOQL appears, the SOQL parser starts to parse the entire file instead of only the `soql_query_body` section. Do you happen to know if it is controlled by a query file to define the nested SOQL scope?

**Comment by aheber** [comment]
Looking at it again, technically Apex imports SOSL but SOSL imported SOQL so that is how SOQL gets into Apex. This is because parts of SOQL are necessary for a SOSL query.

(SOSL importing SOQL)
https://github.com/aheber/tree-sitter-sfapex/blob/31853f4ca3303919e7715b2517df39330baaf6bf/common/sosl-grammar.js#L4

(Apex importing SOSL)
https://github.com/aheber/tree-sitter-sfapex/blob/31853f4ca3303919e7715b2517df39330baaf6bf/apex/grammar.js#L12

**Comment by xixiaofinland** [comment]
I think I almost got the root cause.
https://github.com/nvim-treesitter/nvim-treesitter/issues/5383#issuecomment-1716154581 @aheber

**Comment by aheber** [comment]
It sounds like the parser is good. Now you have the highlights spread out (because that is how I had it)
So copy the highlights from SOQL and SOQL files and paste them into the Apex highlights file and it should work. Then we just have the long term problem of how to maintain that.

If you can confirm it works to start that tells us we're going the right direction.

**Comment by aheber** [comment]
The reason I'm not using injection is mostly because I made the decision that this would be better. Nobody would have to figure out multiple languages and how to jump between.

The other reason is because SOQL and SOSL inside of Apex are not the same things as outside.
How to present search terms, bound variables, etc...

To reflect that I handle those differences in the parser configuration. The Apex parser understands Apex and SOQL inside of Apex is just more Apex.

Maybe it was arbitrary but as I weighed the options this seemed better at the time.

**Comment by xixiaofinland** [comment]
> 

yes, the nested soql highlight works after combining the scm files into one. Though I'm not sure if the namespaces overlap some highlight colors. But those are easy to resolve

**Comment by xixiaofinland** [comment]
> The reason I'm not using injection is mostly because I made the decision that this would be better. Nobody would have to figure out multiple languages and how to jump between.
> 
> The other reason is because SOQL and SOSL inside of Apex are not the same things as outside. How to present search terms, bound variables, etc...
> 
> To reflect that I handle those differences in the parser configuration. The Apex parser understands Apex and SOQL inside of Apex is just more Apex.
> 
> Maybe it was arbitrary but as I weighed the options this seemed better at the time.

it's a design decision and I support it :)

**Comment by xixiaofinland** [comment]
Now, question about the highlight queries.

I see some annotations, like `@function.defaultLibrary`, `@enumMember`,  `@variable.readonly`, and more, they don't exist in my nvim color theme so they fall back the default color.

How did you determine these annotation names? Does it mean I need to learn Nvim theme most often used annotations and map to them? @aheber

**Comment by aheber** [comment]
This is just a difference of standards. I used the semantic set from VSCode and NVIM has a few different ones. You just need to change the highlights tagging to match that document you linked earlier.
This is where we'll start diverging the highlights files for different systems.

**Comment by xixiaofinland** [comment]
> This is just a difference of standards. I used the semantic set from VSCode and NVIM has a few different ones. You just need to change the highlights tagging to match that document you linked earlier. This is where we'll start diverging the highlights files for different systems.


Another question: why not add `parser.c` into the repo so ppl don't need the CLI from `npm` or Rust to generate the final parser? I assume it's cross-platform and everybody gets the same parser.c by given the same grammar.js

**Comment by aheber** [comment]
I'd have to confirm but I think I added it recently. (Either way I do understand now it should be there)

My original thoughts were not committing artifacts, only the raw source. I don't love having to ensure code is compiled at commit and not having a clear assurance that files are in sync.

I didn't realize how much treesitter depends on the GitHub repo to be ready to roll as a deployment mechanism. Now that I understand that better I'm willing to deal with the issues to make the repo more usable.

**Comment by xixiaofinland** [comment]
As we will soon prepare PR to link this repo under the official nvim-tree-sitter, how do we handle the queries conflicts?
Especially nvim-tree-sitter has some queries diverged from upstream

**Comment by xixiaofinland** [comment]
> I'd have to confirm but I think I added it recently. (Either way I do understand now it should be there)
> 
> My original thoughts were not committing artifacts, only the raw source. I don't love having to ensure code is compiled at commit and not having a clear assurance that files are in sync.
> 
> I didn't realize how much treesitter depends on the GitHub repo to be ready to roll as a deployment mechanism. Now that I understand that better I'm willing to deal with the issues to make the repo more usable.

i don't see any `parser.c` in the entire repo :)

**Comment by aheber** [comment]
I think the precedent is ignore my query files and use query files stored in NVIM-treesitter.

This seems like their normal operating procedure. You are only taking my query files as baseline then moving to managing them entirely separate in that NVIM-treesitter repo.

Once you do that we might have to verbally coordinate any significant changes but generally each is optimized for their own interests.

**Comment by aheber** [comment]
> > I'd have to confirm but I think I added it recently. (Either way I do understand now it should be there)
> 
> > 
> 
> > My original thoughts were not committing artifacts, only the raw source. I don't love having to ensure code is compiled at commit and not having a clear assurance that files are in sync.
> 
> > 
> 
> > I didn't realize how much treesitter depends on the GitHub repo to be ready to roll as a deployment mechanism. Now that I understand that better I'm willing to deal with the issues to make the repo more usable.
> 
> 
> 
> i don't see any `parser.c` in the entire repo :)

I'll have to look into it later. It is my intention for it to be there. Probably a commit I made and forgot to push up.

Expect that it'll be fixed as late  as next week, hopefully sooner.

**Comment by xixiaofinland** [comment]
> > > I'd have to confirm but I think I added it recently. (Either way I do understand now it should be there)
> > 
> > 
> > > 
> > 
> > 
> > > My original thoughts were not committing artifacts, only the raw source. I don't love having to ensure code is compiled at commit and not having a clear assurance that files are in sync.
> > 
> > 
> > > 
> > 
> > 
> > > I didn't realize how much treesitter depends on the GitHub repo to be ready to roll as a deployment mechanism. Now that I understand that better I'm willing to deal with the issues to make the repo more usable.
> > 
> > 
> > i don't see any `parser.c` in the entire repo :)
> 
> I'll have to look into it later. It is my intention for it to be there. Probably a commit I made and forgot to push up.
> 
> Expect that it'll be fixed as late as next week, hopefully sooner.

not in any hurry at all!
