### ISSUE TITLE
Alias usage in `TYPEOF` not supported.

### ISSUE THREAD

**Issue by sam-superframe** [aheber/tree-sitter-sfapex#19]
I've been kicking around some edge cases in SOQL queries and I think I found an issue where aliases are not supported in `TYPEOF` statements in the parser, but they seem to be supported in Salesforce Apex/SOQL.

I tested out the following Apex code in a test instance, and it ran successfully.

```
SObject[] stuffs = [
  Select Id, TypeOf c.Owner WHEN Group Then Type Else Id, Name End From Case c
];

System.debug(stuffs.size());

for(Integer i = 0; i < stuffs.size(); i++) {
  SObject myObject = stuffs[i];
  Map<String, Object> fieldMap = myObject.getPopulatedFieldsAsMap();
  for (String fieldName : fieldMap.keySet()) {
    Object fieldValue = fieldMap.get(fieldName);
    System.debug('Field Name: ' + fieldName + ', Field Value: ' + fieldValue);
  }
}
```

It would appear that the parser is unhappy with the `c.Owner` alias usage in the `TypeOf` section.

<img width="1462" alt="image" src="https://github.com/aheber/tree-sitter-sfapex/assets/144175472/d0b05e15-3833-402d-85bf-40378927ad34">

**Comment by aheber** [comment]
Lots of great edge cases today, I love it!

That one is a pretty easy fix, I've got a test and fix ready for it.

**Comment by sam-superframe** [comment]
Thanks for getting to this so quickly!
