### ISSUE TITLE
Missing DML `as user` syntax support.

### ISSUE THREAD

**Issue by sam-superframe** [aheber/tree-sitter-sfapex#21]
I've been putting all of the code examples located in [this repo](https://github.com/trailheadapps/apex-recipes) through the Apex parser, and it seems that there is an undocumented (in the [Apex DML docs](https://developer.salesforce.com/docs/atlas.en-us.apexcode.meta/apexcode/langCon_apex_dml_operations.htm)) syntax variant that appears as follows:

```
update as user decision.getRecords();
```

In the attached fixtures, you will find references to each of the following:

```
update as...
insert as...
upsert as...
delete as...
undelete as...
```

As far as I'm aware, there is only one other DML statement that does not appear in any of the apex examples provided in the linked repo above. That is the `merge` statement. But, I was able to compile the following snippet into a class, which strongly supports the existence of `merge as...` syntax also being valid.

```
public with sharing class MergeTest {
    
    public static void someMethod() {
        Account masterAcct = [SELECT Id, Name FROM Account WHERE Name = 'Acme Inc.' LIMIT 1];
        Account mergeAcct = [SELECT Id, Name FROM Account WHERE Name = 'Acme' LIMIT 1];

        try {
            merge as user masterAcct mergeAcct;
        } catch (DmlException e) {
            // Process exception
            System.debug('An unexpected error has occurred: ' + e.getMessage()); 
        }
    }
}
```

Currently, the APEX parser will generate a tree with an error node, though these snippets seem to all be valid.

[dml_errors.zip](https://github.com/aheber/tree-sitter-sfapex/files/13721913/dml_errors.zip)

**Comment by aheber** [comment]
You're right, I did most of this work before the 'as' was GA and I forgot to go back and implement it. I'll get it done shortly, thanks for reminding me!

**Comment by aheber** [comment]
The documentation for the syntax is mostly contained here, https://developer.salesforce.com/docs/atlas.en-us.apexcode.meta/apexcode/apex_classes_enforce_usermode.htm

I've added support in v0.0.11 which is now the current version in the playground and in NPM. This adds the new `dml_security_mode` node type to represent the `user` or `system` text value.
