### ISSUE TITLE
New ?? Null Coalescing Operator support

### ISSUE THREAD

**Issue by xixiaofinland** [aheber/tree-sitter-sfapex#24]
Hi Anthony, do you have a plan to support it in the Apex parser?

**Comment by aheber** [comment]
I have the changes built and tested on my computer, I did it a bit ago. I just forgot to push it up, I'll do that today.

**Comment by aheber** [comment]
I lied, it is in there.
https://github.com/aheber/tree-sitter-sfapex/blob/857077f9e6bb04df0f769c18d32bfe036911adc8/apex/test/corpus/operators.txt#L401
[v0.0.12](https://github.com/aheber/tree-sitter-sfapex/commit/857077f9e6bb04df0f769c18d32bfe036911adc8) includes it.

If you're seeing something different please let me know.

**Comment by xixiaofinland** [comment]
Ahh, it is indeed already supported!
You are so ahead of time❤
