### ISSUE TITLE
Rules accepted by sfapex parser but not jorje

### ISSUE THREAD

**Issue by xixiaofinland** [aheber/tree-sitter-sfapex#32]
Using this thread to list down findings on this category.

`do_statement` can't parse without `{ }` in jorje but accepted in sfapex parser.
```
public class Me {
  {
    do 
      Integer i = 1;
     while (true);
  }
}
```

**Comment by xixiaofinland** [comment]
the `,` in the annotation element list

```
@Annotation(param1=false, param2='hello')
public class Me {
}
```

**Comment by aheber** [comment]
Thanks for finding these! I'll have fixes included today. I'll leave this open if you want to include anything else you find.

**Comment by xixiaofinland** [comment]
all good now!
