### ISSUE TITLE
java:java syntax?

### ISSUE THREAD

**Issue by xixiaofinland** [aheber/tree-sitter-sfapex#37]
I'm not sure what is this `java:java` pattern here but it parses successfully in prettier apex fails in sfapex.
Up to you to investigate and decide.

```
public class Java {
  public void testJavaVariable() {
    Integer i = java:java.lang.Integer.MAX_VALUE;
    List<Integer> l = java:java.util.Collections.EMPTY_LIST;
  }

  public void testJavaMethod() {
    Integer i = java:java.lang.Integer.valueOf(1729);
    List<Integer> l = java:java.util.Collections.emptyList();
    java:java.util.List propList = new java:java.util.ArrayList();
    java:java.util.Collections.copy(propList, propList);
    java:java.util.Collections.copy(null, null, null, null, null, null, null, null, null, null, null);
  }

// Test that we properly convert types for java constructors
  public void testNewObject() {
    new java:java.lang.Double(0);
    new java:java.lang.Double(0l);
    new java:java.lang.Double(0.0d);
  }
}
```

**Comment by aheber** [comment]
Can this, or something with this pattern, be pushed into Salesforce?

I'm less worried about matching Prettier and more if the platform will accept it. If you can find an example of Salesforce accepting it then we'll figure out what it means and how to add it.

In quick searching I don't see an obvious explainer of what that might mean. I'll keep looking, might be some way of referencing down into the Java layer but over never come across it.

**Comment by aheber** [comment]
https://github.com/dangmai/prettier-plugin-apex/issues/35

I guess internally it is a thing.

Yeah, we should probably figure out how to add support.

**Comment by xixiaofinland** [comment]
good finding!

No hurry at all, I have never ever used this syntax :D

**Comment by aheber** [comment]
This is available now.

**Comment by aheber** [comment]
Fun fact, if you try and save this into Salesforce it gives `Java expression only allowed for trusted sources`
