### ISSUE TITLE
webService keyword not supported

### ISSUE THREAD

**Issue by xixiaofinland** [aheber/tree-sitter-sfapex#39]
It is in prettier not here.

```
class A {
  webService static decimal c() {
  }
}
```

**Comment by aheber** [comment]
Interesting! I had no idea this was a valid keyword. I'll get it added.

**Comment by xixiaofinland** [comment]
I wouldn't know either... Found it as I'm running against a couple of apex repos and going through the parsing/formatting errors


https://github.com/xixiaofinland/afmt/blob/main/tests/battle_test/repos.txt

**Comment by aheber** [comment]
This is available now.

**Comment by xixiaofinland** [comment]
confirm it works!
