### ISSUE TITLE
"> =" not supported

### ISSUE THREAD

**Issue by xixiaofinland** [aheber/tree-sitter-sfapex#40]
Prettier will remove the spaces between `>` and `=` and format them into `>=`. I assume the same goes to `<=` and other possible scenarios.

IMO, we should have the same behavior.

```
public class A {
  {
    if (i >   = 0) {   
    }
  }
}
```

**Comment by aheber** [comment]
Looks like Jorje/Salesforce will accept code written that way, agree that we should as well. Shouldn't be a huge change to the grammar but might impact some of the highlighting and such that looks for those characters together.

I'll get it done shortly.

**Comment by aheber** [comment]
This one was incredibly odd. There are only a handful of operators that Jorje/Salesforce will accept like this. For instance you can't change `==` into `= =` but you can change `<<=` into `< < =`.

I tested everything but added code tests for the ones that worked when pushed to Salesforce.

This should be working correctly now.

**Comment by xixiaofinland** [comment]
confirm it works!
