### ISSUE TITLE
Missing info in version_expression node

### ISSUE THREAD

**Issue by xixiaofinland** [aheber/tree-sitter-sfapex#47]
version_expression node doesn't have the child node corresponding to the value "1.0"

```
class P {
  {
    Object v = Package.Version.1.0; 
  }
}
```

**Comment by aheber** [comment]
@xixiaofinland to make sure I understand. You would like there to be a child node, maybe with a field name, that is just the `1.0` value?

So in the current form we have:
```Apex
class P {
  {
    Object v = Package.Version.1.0; 
                       ^^^^^^^^^^^^^^^ version_expression
  }
}
```
and you propose something more like:

```Apex
class P {
  {
    Object v = Package.Version.1.0; 
                       ^^^^^^^^^^^^^^^ (version_expression)
                                                    ^^ version: (version_number)
  }
}
```

**Comment by xixiaofinland** [comment]
You are right :)!

My challenge with the formatter occurs when the code contains potential whitespaces, such as version_expression node value can be `Package.    Version.    1.0`. 

I need to be able to identify `Package`, `Version`, and `1.0`, and concatenate them back, preferably without using any unnamed nodes. 

Currently, the bottom named node is `version_expression`, which includes these extraneous blanks. The unnamed child nodes of it do not retain the specific information `1.0`. Thus it seems that I cannot achieve what I need.

**Comment by aheber** [comment]
This is published now.
