### ISSUE TITLE
SOQL parsing failure

### ISSUE THREAD

**Issue by xixiaofinland** [aheber/tree-sitter-sfapex#48]
I'm horrible on complex SOQL, just run into this which works in PA while not in sfapex. Not sure if it's a valid query though...

```
class T {
  {
    [
      SELECT Id
      FROM Lead
      GROUP BY LeadSource
      HAVING COUNT(Name) > 100 AND LeadSource LIKE 'San%'
    ];
  }
}
```

**Comment by aheber** [comment]
It is really close to valid, needs an aggregate function on the selected Id field.
```soql
SELECT COUNT(Id)
FROM Lead
GROUP BY LeadSource
HAVING COUNT(Name) > 100 AND LeadSource LIKE 'San%'
```

I have never used a non-function in the HAVING clause and hadn't seen this until you posted it. I'll probably have to re-think what the HAVING clause is allowed to do. 

As you already know it has it's own variant structures that are similar to the WHERE clause but are more restrictive. I may have to undo that layer and allow everything the WHERE clause can do in the HAVING clause. Beyond parsing, Salesforce will enforce everything in the HAVING as being an aggregate value, LeadSource being in the `GROUP BY` is what allows this query to actually execute.

I'm not sure the edges of this so I'll have to look into it and do some additional testing. I suspect in the end I'll have to make the HAVING and WHERE clauses support the same syntax. Probably good news from a formatting point of view.

**Comment by aheber** [comment]
I never enjoyed having the various `having_...` variants so needing to rip them out will bring me joy. HAVING expressions aren't very common but they do get used regularly. Not sure how often anyone will be depending on them. This will be a pretty large change tearing out a large number of nodes but it should simplify a lot of things across the board.

I was able to build a more complicated query using the same basic structure and execute it against the platform. I think this justifies the need to normalize the `WHERE` and `HAVING` expression syntax.

```soql
SELECT COUNT(Id)
FROM Lead
GROUP BY LeadSource
HAVING (COUNT(Name) > 100 AND LeadSource LIKE 'San%') OR (LeadSource = 'San%' AND LeadSource IN ('Val1', 'Val2'))
```

**Comment by aheber** [comment]
This is published now.
