### ISSUE TITLE
locating children nodes in dml_expression variants

### ISSUE THREAD

**Issue by xixiaofinland** [aheber/tree-sitter-sfapex#49]
Afmt has the challenge of differentiating and locating the two children (`$.expression, optional($._unannotated_type)`) in 2nd variant, and the two children (`$.expression, $.expression`) in 3rd variant.  Currently, I need to locate them using [code here](https://github.com/xixiaofinland/afmt/blob/83bec4f9f615b6d437f350d75415af0213dcf82f/src/data_model.rs#L2052).

Most of times, I use the child placeholder name or child kind name to locate children without looping them(which is less precise and error-prone). `$.expression` and `$._unannotated_type` are both general grouping nodes, and there is no placeholder name to locate them. 

```
    dml_expression: ($) =>
      prec.right(
        choice(
          seq(
            $.dml_type,
            optional(seq(ci("as"), $.dml_security_mode)),
            $.expression
          ),
          seq(
            alias($.upsert_dml_type, $.dml_type),
            optional(seq(ci("as"), $.dml_security_mode)),
            $.expression,
            optional($._unannotated_type)
          ),
          seq(
            alias($.merge_dml_type, $.dml_type),
            optional(seq(ci("as"), $.dml_security_mode)),
            $.expression,
            " ",
            $.expression
          )
        )
      ),
```

**Comment by aheber** [comment]
Here is my proposed change, this adds named fields to most of the variable portions.

That should make it easy to check for the `security_mode`, identify the `target`, `upsert_key` and `merge_with` fields when available.

```javascript
dml_expression: ($) =>
      prec.right(
        choice(
          seq(
            $.dml_type,
            optional(field("security_mode",seq(ci("as"), $.dml_security_mode))),
            field("target", $.expression)
          ),
          seq(
            alias($.upsert_dml_type, $.dml_type),
            optional(field("security_mode",seq(ci("as"), $.dml_security_mode))),
            field("target", $.expression),
            optional(field('upsert_key',$._unannotated_type))
          ),
          seq(
            alias($.merge_dml_type, $.dml_type),
            optional(field("security_mode",seq(ci("as"), $.dml_security_mode))),
            field("target", $.expression),
            " ",
            field("merge_with", $.expression)
          )
        )
      ),
```

If that will make it easy to identify the necessary pieces I can make that change. Let me know.

**Comment by xixiaofinland** [comment]
This would greatly simplify my logic check ❤

**Comment by aheber** [comment]
This is published now.

**Comment by xixiaofinland** [comment]
works!
