### ISSUE TITLE
Add to Apex support to nvim-treesitter

### ISSUE THREAD

**Issue by aheber** [aheber/tree-sitter-sfapex#5]
Need to customize query files and get registered. Ref: https://github.com/nvim-treesitter/nvim-treesitter/issues/2282

**Comment by aheber** [comment]
Rough outline of steps needed to make it work manually, without it being "known" by `nvim-treesitter`

Had to download the tree-sitter-sfapex repo to my machine

Enable syntax `syntax on`

Register File Types:
```
augroup FileTypeGroup
	au BufRead,BufNewFile *.cls,*.trigger,*.apex set filetype=apex
	au BufRead,BufNewFile *.soql set filetype=soql
	au BufRead,BufNewFile *.sosl set filetype=sosl
augroup END
```

Run LUA to register the custom repos

```
lua <<EOF

local parser_config = require "nvim-treesitter.parsers".get_parser_configs()
parser_config.apex = {
  install_info = {
    url = "{{installpath}}/tree-sitter-apex/apex", -- local path or git repo
    files = {"src/parser.c"},
    branch = "main", -- default branch in case of git repo if different from master
    generate_requires_npm = false, -- if stand-alone parser without npm dependencies
    requires_generate_from_grammar = true, -- if folder contains pre-generated src/parser.c
  }
}

parser_config.soql = {
  install_info = {
    url = "{{installpath}}/tree-sitter-apex/soql", -- local path or git repo
    files = {"src/parser.c"},
    branch = "main", -- default branch in case of git repo if different from master
    generate_requires_npm = false, -- if stand-alone parser without npm dependencies
    requires_generate_from_grammar = true, -- if folder contains pre-generated src/parser.c
  }
}

parser_config.sosl = {
  install_info = {
    url = "{{installpath}}/tree-sitter-apex/sosl", -- local path or git repo
    files = {"src/parser.c"},
    branch = "main", -- default branch in case of git repo if different from master
    generate_requires_npm = false, -- if stand-alone parser without npm dependencies
    requires_generate_from_grammar = true, -- if folder contains pre-generated src/parser.c
  }
}

require'nvim-treesitter.configs'.setup {
  ensure_installed = {"apex","sosl","soql"}, -- one of "all", "maintained" (parsers with maintainers), or a list of languages
  ignore_install = {}, -- List of parsers to ignore installing
  highlight = {
    enable = true,              -- false will disable the whole extension
    disable = {},  -- list of language that will be disabled
    -- Setting this to true will run `:h syntax` and tree-sitter at the same time.
    -- Set this to `true` if you depend on 'syntax' being enabled (like for indentation).
    -- Using this option may slow down your editor, and you may see some duplicate highlights.
    -- Instead of true it can also be a list of languages
    additional_vim_regex_highlighting = false
  }
}

EOF
```

Had to copy the query files from the repo into plugin dir's Query/[apex,soql,sosl]/*.scm files (had to merge different files together, could probably use merge syntax though as-if inherited lang)

`:TSInstall apex`
`:TSInstall soql`
`:TSInstall sosl`

**Comment by noenthu** [comment]
Appreciate your effort. One question regarding setting the filetype for apex. The nvim-lspconfig now has an apex_ls which expects the ft to be apexcode. However, the lsp does not provide semantic highlighting.

**Comment by aheber** [comment]
@noenthu, I'm not sure the question you're asking but I'll answer what I think you're getting at.

I don't have a need for it to be `apex` as the FT, after I announced this project I had someone reach out and ask if I could get it working in NVIM. These notes are the product of my efforts. I will still need to go determine the correct way to go about things as well as adapt my queries to NVIM's needs. I don't use NVIM personally so I'll depend on others and the `nvim-treesitter` project to help shape the outcomes.

If the correct expectation will be to use `apexcode` as the FT then so be it.

**Comment by Astisme** [comment]
@aheber could you please explain where did you make those changes? Is it the .vimrc?

**Comment by aheber** [comment]
@Astisme, yes `init.vim` or wherever your installation looks for configuration scripts.

**Comment by mccheesy** [comment]
Excellent work on this and thanks for sharing it! Just wanted to chime in after trying having some minor trouble getting it working in Neovim v0.9 (nightly) and nvim-treesitter.

I received an error when adding the queries to nvim-treesitter:
```
- ERROR apex(highlights): ...-19591e9/share/nvim/runtime/lua/vim/treesitter/query.lua:219: query: invalid structure at position 2629 for language apex
  apex(highlights) is concatenated from the following files:
  | [ERROR]:"~/.local/share/nvim/site/pack/packer/start/nvim-treesitter/queries/apex/highlights.scm", failed to load: ...-19591e9/share/nvim/runtime/lua/vim/treesitter/query.lua:219: query: invalid structure at position 2629 for language apex
```
It seems like the `bound_apex_expression` is what's throwing off nvim-treesitter. When I comment lines 141-142 of the apex/highlights.scm file and rerun :TSUpdate, highlights start working properly. Not sure whether this helps as I'm very new to treesitter, but thought I'd drop this here in case anyone else ran into the same issue.

**Comment by xixiaofinland** [comment]
> 

do you still get such an error? I don't see such an error after successfully configuring it.

**Comment by mccheesy** [comment]
Yes, still getting the same error. Something about
```
(bound_apex_expression
  (identifier) @variable)
```
seems to be detected by query.lua as 'invalid structure'. Not quite sure how to troubleshoot this one as I don't know much about treesitter grammar or Scheme language. I mentioned before commenting out lines 141-142 fixing the issue, but it doesn't appear to work for me anymore. The only change I've made is setting `const LANG = "apexcode"` in apex/grammar.js to correspond to the filetype in Neovim that's also used for apex_ls.

Happy to provide any more details that could help with solving this issue.

**Comment by xixiaofinland** [comment]
> bound_apex_expression

Actually, `bound_apex_expression` is not defined in the `grammar.js` file. That's the reason why the query can't locate this correctly. So the error is expected. You can simply delete the `bound_apex_expression` section from the `highlights.scm`. 
  
Maybe Anthony updated the token name but forgot to update the `highlights.scm`. He is not a nvim user.

How the tree-sitter query works is that it uses the token names (such as `bound_apex_expression`)  parsed by the parser to locate element in the AST (in nvim you can run `:InspectTree` to see the AST of the current buffer, including all the token names).

I plan to dig into this repo, fork, and extend on top of it.

**Comment by aheber** [comment]
I'm not sure why that line is throwing an error. As for `bound_apex_expression` it is part of the SOQL common parser which is imported both into the SOQL grammar and Apex grammar. 
https://github.com/aheber/tree-sitter-sfapex/blob/31853f4ca3303919e7715b2517df39330baaf6bf/common/soql-grammar.js#L423
The SOQL grammar doesn't enable it but Apex does (bound variables are only available in one of those contexts).
Deleting that highlighting rule likely wouldn't have any significant negative consequences.

I'll see if I can find a root cause but it may be a bit before I get NVIM setup for testing again (not a daily driver for me)

**Comment by xixiaofinland** [comment]
> I'm not sure why that line is throwing an error. As for `bound_apex_expression` it is part of the SOQL common grammar which is imported both into the SOQL grammar and Apex grammar.
> 
> https://github.com/aheber/tree-sitter-sfapex/blob/31853f4ca3303919e7715b2517df39330baaf6bf/common/soql-grammar.js#L423
> 
> 
> The SOQL grammar doesn't enable it but Apex does (bound variables are only available in one of those contexts).
> Deleting that highlighting rule likely wouldn't have any significant negative consequences.
> I'll see if I can find a root cause but it may be a bit before I get NVIM setup for testing again (not a daily driver for me)

ah, it's part of SOQL. 
The SOQL inside Apex is recognized by the parser, but the SOQL highlights are not.  It might need to do something in Nvim to enable language injection.

@mccheesy do you get the error in Apex without SOQL as well?  It shouldn't be the case.

**Comment by xixiaofinland** [comment]
I can't reproduce this error.  It works for me, screenshot below (tree left, apex middle, highlights right)
[screenshot](https://ibb.co/TL4GBdw)

**Comment by xixiaofinland** [comment]
I can't reproduce this error.  It works for me, screenshot below (tree left, apex middle, highlights right)

![Image 002](https://github.com/aheber/tree-sitter-sfapex/assets/13655323/ec17f78c-a810-4a07-92cc-c4a22b6fa058)

**Comment by aheber** [comment]
Huge thanks to @xixiaofinland for getting Apex, SOQL, and SOSL formally added to nvim-treesitter. I'm going to go ahead and close this ticket now. 

If additional issues come up please recognize that the queries (choosing which parts of the parsed tree to select & highlight) are now managed inside the nvim-treesitter repo. The only thing being used from this repo is the generated parser code, issues with how Apex is parsed can come here but will be expected to be reproducible in the playground or in tests.
