### ISSUE TITLE
locating children nodes in catch_formal_parameter

### ISSUE THREAD

**Issue by xixiaofinland** [aheber/tree-sitter-sfapex#50]
In order to locate `$._unannotated_type`, I need to locate the node with placeholder name "name" in `$._variable_declarator_id`, then check it's previous node and assume it's the _unannotated_type.

This is the only place I need to use "get_previous_node()", wonder if it makes sense to give a place_holder name to the `$._unannotated_type`?

```
    catch_formal_parameter: ($) =>
      seq(
        optional($.modifiers),
        $._unannotated_type,
        $._variable_declarator_id
      ),
```

**Comment by aheber** [comment]
I'm going to remove `catch_formal_parameter` and use the existing `formal_parameter` which already contains a field of `type`, having that field assigned is the only difference between them. I see no reason to keep them separate and I couldn't tell you why they were separated in the first place.

The node structure of `catch_clause` will now be
```javascript
catch_clause: ($) =>
  seq(
    ci("catch"),
    "(",
    $.formal_parameter,
    ")",
    field("body", $.block)
  ),
```

**Comment by aheber** [comment]
This is published now.
