### ISSUE TITLE
GEOLOCATION in SOQL parsing fails

### ISSUE THREAD

**Issue by xixiaofinland** [aheber/tree-sitter-sfapex#52]
This works in [PA](https://apex.dangmai.net/#N4Ig9gDgLglmB2BnEAuUEwCcqoCy4GYAaEACzERxRAEMIBTADwFobKA6BTe+AE3szsAxmAC2IEhExgoYEQBtUZKFAjJJNTIgFK6TCSCkx4UAOoxeUUqgAcABhJQaAI3OXrKAEwkArtoAqLsgoAGY08tokeowAkkgCUABixuEAcvQA7vLG9KhQmD70AL4kIvxKQvJsiAAEAII1wAA68DU1AG5gFjXa8vRCUAAiMJQ08EL0AKKMUvSIiHDwABQAlI0tbW0AygLtMBMA+gdCPbv79DUAvDUA2hub25MAMpMAwv73D20WRJ9fgzEtv46qlXpMln8vjUnnIaLAEEchL9WlDNgBxSYAeSemNedX8MUxqSWKEqMB4UHYMKEcMWRyetKgPn4R0QyNRX1J2QpVNh8Pg9IQAHMYEyWQdEJCvit2RyagByUQweVStprXgjKBSxIAJUxAFkajtMHtDscpaYABKTHWTVU1AFAkFgiEojnU2kI46yjkY7G4-GE4lc8kmXk0-n0xnM+isn1ykM8j2Rg4w+AisWxiX2tXxqGK5X2tYAHhqKH4YR88ig+pojGGo3G9D+AF0ANz3IotLvwEBFIA) but throws error in sfapex around GEOLOCATION.

```
class A {
  void selectDistanceExpression() {
    Service__c service = [
      SELECT
        id,
        DISTANCE(
          Location__c,
          GEOLOCATION(:client.Location__Latitude__s,
            :client.Location__Longitude__s
          ),
          'mi'
        ) dist
      FROM Service__c
      WHERE
        DISTANCE(
          Location__c,
          GEOLOCATION(:client.Location__Latitude__s,
            :client.Location__Longitude__s
          ),
          'mi'
        ) < :defaultMaxDistance
    ];
  }
}
```

**Comment by aheber** [comment]
Thanks, shouldn't be too hard to fix. The DISTANCE and GEOLOCATION functions have special handling and I probably didn't teach them to handle bound expressions.

**Comment by aheber** [comment]
Should be updated now. Will update the NPM package later.

**Comment by xixiaofinland** [comment]
works!
