### ISSUE TITLE
SOSL should allow multiple WITH statements

### ISSUE THREAD

**Issue by aheber** [aheber/tree-sitter-sfapex#57]
A SOSL query should allow multiple WITH statements

This should be valid SOSL but is not parsed correctly by `sfapex`

```
FIND { Hello }
  WITH PriceBookId = '01sxx0000002MffAAE'
  WITH PriceBookId = '01sxx0000002MffAAE'
  WITH PriceBookId = '01sxx0000002MffAAE'
```

_Originally posted by @xixiaofinland in https://github.com/aheber/tree-sitter-sfapex/issues/54#issuecomment-2536700119_

**Comment by aheber** [comment]
The original issue reported the following as valid, 

```
FIND {Hello}
    RETURNING Product2
    WITH PriceBookId IN ('01sxx0000002MffAAE', '1234')
```

If I try and run this in an org I receive the following error:
```
IN cannot be used for WITH PriceBookId clause
```

So this looks parse-able but not executable. I think I'm going to choose not to add support.

I will still add support for multiple `WITH` statements in a query.

**Comment by aheber** [comment]
Should be updated now. Will update the NPM package later.

**Comment by xixiaofinland** [comment]
works!
