### ISSUE TITLE
Child super nodes && align method_invocation with field_access

### ISSUE THREAD

**Issue by xixiaofinland** [aheber/tree-sitter-sfapex#58]
1. It'd be nice to be able to differentiate the two `super` nodes easily, such as a placeholder name for "optional(seq($.super, $._property_navigation))"?

Currently, in order to know whether the 2nd `super` exists or not, I need to check the number of `super` child nodes first, code [here](https://github.com/xixiaofinland/afmt/blob/000f9e700e2aa9f42885da70bf36be3f93d85225/src/data_model.rs#L903).

```
    method_invocation: ($) =>
      seq(
        choice(
          field("name", $.identifier),
          seq(
            field("object", choice($.primary_expression, $.super)),
            $._property_navigation,
            optional(seq($.super, $._property_navigation)),
            field("type_arguments", optional($.type_arguments)),
            field("name", $.identifier)
          )
        ),
        field("arguments", $.argument_list)
      ),
```

Code example:
```
class A {
  {
    a[0].super?.c();
    super?.b().c;
  }
}
```

**Comment by xixiaofinland** [comment]
same goes to `field_access` node

```
    field_access: ($) =>
      seq(
        field("object", choice($.primary_expression, $.super)),
        optional(seq($._property_navigation, $.super)),
        $._property_navigation,
        field("field", choice($.identifier, $.this))
      ),
```

**Comment by aheber** [comment]
I'll have to go over these again. This should be simpler. Maybe I can remember what past me what thinking.

That optional section seems completely redundant when I would expect it to drill down and just nest another field access on the next layer.

I'll check, maybe it had a hard time parsing some structures?

We should be able to clean this up. I'll try and give it some time this weekend.

**Comment by aheber** [comment]
I've removed the optional super chains. It should now be cleaner. I didn't see any problem in tests. Let me know if I broke anything on your end.

**Comment by xixiaofinland** [comment]
I never see real code with `super` in the middle, so I don't know what it means semantically. But the two `super` are treated as `identifier` and `super` nodes respectively, this is correct?

```
class A {
  {
    a.super.Set();

    super.a.set();
  }
}
```

**Comment by xixiaofinland** [comment]
Nonetheless, I confirm it works on my end as well. Good logic simplification!
