### ISSUE TITLE
optional(ci) node in alias_expression

### ISSUE THREAD

**Issue by xixiaofinland** [aheber/tree-sitter-sfapex#59]
It seems no good way to determine if `ci("AS")` exists or not. The best solution is to check the child node source code if it matches "AS".

Shall we add a placeholder name for it? 

```
      alias_expression: ($) =>
        seq($._value_expression, optional(ci("AS")), $.identifier),
```

**Comment by xixiaofinland** [comment]
I just tested it in [PA](https://apex.dangmai.net/#N4Ig9gDgLglmB2BnEAuUEwCcqoCy4GYAaEACzERxRAEMIBTADwFobKA6BTe+AE3szsAxmAC2IEhExgoYEQBtUZKFAjJJNTIgFK6TCSCkx4UAOoxeUUqgAcABhJQaAI3OXrKAEwkArtoAqLsgoAGY08tokeowAkkgCUABixuEAcvQA7vLG9KhQmD70AL4kIvxKQvJsiAAEAII1wAA68DWNLW1tANoAygCiADJ9AML+NQCyNIwAFHUAlGw1w3VENTG8NYkASgDy4zU7EBjYPvAwUACeNQDiuwCqAAo1AEIAmmu8ALoA3B01RS0iiAikA)

It seems "AS" is not supported in jorje, shall we remove it well?

**Comment by aheber** [comment]
I think you are right. I can't get anything to work that has it. I'll remove it.

I will note that you've only mentioned `alias_expression` and I agree, it looks incorrect. You'll have a similar problem with `storage_alias` which is actually allowed to have an `AS`.

This one does run `SELECT c.Id, c.Name FROM Contact as c`

I don't think you need to worry too much about it. The `AS` doesn't change behavior at all and from a formatter perspective I would only expect you to be consistent in adding or removing it, not persisting a users preference here. I'm sure someone somewhere will disagree with me given enough time.

**Comment by aheber** [comment]
This should be published to the repo now.

**Comment by xixiaofinland** [comment]
Thanks for notifying me, PA also automatically removes `as` in `storage_alias` in case the user has put it in, I will follow this.

**Comment by xixiaofinland** [comment]
I confirm that both nodes are working on my end.
